canonifyurls = true
title = "Water Data Labs"
name = ["Jim Kreft"]
email = ["jkreft@usgs.gov"]
paginate = 100
theme = "wdfn_theme"
disableKinds=["taxonomyTerm"]


[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true