version: "3"

services:
  hugo_base:
    build: ./
  hugo:
    build:
      context: ./
      dockerfile: Dockerfile_hugo
    command: tail -F anything
    ports:
      - "1313:1313"
    volumes:
      - .:/src
